import argparse
import re
import sys

def parse_args():
    parser = argparse.ArgumentParser(description='Convert MariaDB SQL to other DB formats.')
    parser.add_argument('--target', type=str, required=True, choices=['postgres', 'sqlserver', 'oracle', 'sqlite'])
    parser.add_argument('--input', type=str, required=True)
    parser.add_argument('--output', type=str, required=True)
    return parser.parse_args()

def clean_type(line, target):
    # Regex for types
    # Handle auto_increment/identity first
    if target == 'postgres':
        if 'AUTO_INCREMENT' in line:
            # Serial implies integer and auto-increment
            line = re.sub(r'\bint\(\d+\)\s+NOT NULL\s+AUTO_INCREMENT', 'SERIAL', line, flags=re.IGNORECASE)
            line = re.sub(r'\btinyint\(\d+\)\s+NOT NULL\s+AUTO_INCREMENT', 'SMALLSERIAL', line, flags=re.IGNORECASE)
            # Cleanup remnants just in case
            line = line.replace('AUTO_INCREMENT', '')
        
        # Standard type mapping
        line = re.sub(r'\btinyint\(\d+\)', 'SMALLINT', line, flags=re.IGNORECASE)
        line = re.sub(r'\bint\(\d+\)', 'INTEGER', line, flags=re.IGNORECASE)
        line = re.sub(r'\bmediumtext\b', 'TEXT', line, flags=re.IGNORECASE)
        line = re.sub(r'\blongtext\b', 'TEXT', line, flags=re.IGNORECASE)
        line = re.sub(r'\bdatetime\b', 'TIMESTAMP', line, flags=re.IGNORECASE)
        line = re.sub(r'\btimestamp\b', 'TIMESTAMP', line, flags=re.IGNORECASE)
        
        # Defaults
        line = line.replace('current_timestamp()', 'CURRENT_TIMESTAMP')
        line = re.sub(r'ON UPDATE CURRENT_TIMESTAMP', '', line, flags=re.IGNORECASE)

    elif target == 'sqlserver':
        if 'AUTO_INCREMENT' in line:
            line = re.sub(r'\bint\(\d+\)\s+NOT NULL\s+AUTO_INCREMENT', 'INT IDENTITY(1,1) NOT NULL', line, flags=re.IGNORECASE)
            line = re.sub(r'\btinyint\(\d+\)\s+NOT NULL\s+AUTO_INCREMENT', 'TINYINT IDENTITY(1,1) NOT NULL', line, flags=re.IGNORECASE)
        
        line = re.sub(r'\btinyint\(\d+\)', 'TINYINT', line, flags=re.IGNORECASE)
        line = re.sub(r'\bint\(\d+\)', 'INT', line, flags=re.IGNORECASE)
        line = re.sub(r'\btext\b', 'NVARCHAR(MAX)', line, flags=re.IGNORECASE)
        line = re.sub(r'\bmediumtext\b', 'NVARCHAR(MAX)', line, flags=re.IGNORECASE)
        line = re.sub(r'\blongtext\b', 'NVARCHAR(MAX)', line, flags=re.IGNORECASE)
        line = re.sub(r'\btimestamp\b', 'DATETIME2', line, flags=re.IGNORECASE)
        line = re.sub(r'\bdatetime\b', 'DATETIME2', line, flags=re.IGNORECASE)
        # Handle boolean
        line = re.sub(r'\bboolean\b', 'BIT', line, flags=re.IGNORECASE)
        
        line = line.replace('current_timestamp()', 'GETDATE()')
        line = re.sub(r'ON UPDATE GETDATE\(\)', '', line, flags=re.IGNORECASE)

    elif target == 'oracle':
        if 'AUTO_INCREMENT' in line:
            # Oracle 12c+
            line = re.sub(r'\bint\(\d+\)\s+NOT NULL\s+AUTO_INCREMENT', 'NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY', line, flags=re.IGNORECASE)
        
        line = re.sub(r'\bint\(\d+\)', 'NUMBER', line, flags=re.IGNORECASE)
        line = re.sub(r'\btinyint\(\d+\)', 'NUMBER(3)', line, flags=re.IGNORECASE)
        line = re.sub(r'\btext\b', 'CLOB', line, flags=re.IGNORECASE)
        line = re.sub(r'\bmediumtext\b', 'CLOB', line, flags=re.IGNORECASE)
        line = re.sub(r'\blongtext\b', 'CLOB', line, flags=re.IGNORECASE)
        line = re.sub(r'\bvarchar\(', 'VARCHAR2(', line, flags=re.IGNORECASE)
        line = re.sub(r'\bdatetime\b', 'DATE', line, flags=re.IGNORECASE)
        
        line = line.replace('current_timestamp()', 'CURRENT_TIMESTAMP')
        line = re.sub(r'ON UPDATE CURRENT_TIMESTAMP', '', line, flags=re.IGNORECASE)
        
        # Remove IF NOT EXISTS for Oracle CREATE TABLE
        line = line.replace('IF NOT EXISTS', '')

    elif target == 'sqlite':
        if 'AUTO_INCREMENT' in line:
            line = re.sub(r'\bint\(\d+\)\s+NOT NULL\s+AUTO_INCREMENT', 'INTEGER PRIMARY KEY AUTOINCREMENT', line, flags=re.IGNORECASE)
        
        line = re.sub(r'\bint\(\d+\)', 'INTEGER', line, flags=re.IGNORECASE)
        line = re.sub(r'\btinyint\(\d+\)', 'INTEGER', line, flags=re.IGNORECASE)
        
        line = line.replace('current_timestamp()', 'CURRENT_TIMESTAMP')
        line = re.sub(r'ON UPDATE CURRENT_TIMESTAMP', '', line, flags=re.IGNORECASE)
    
    # Common Validations
    # Remove MySQL specific charsets and comments
    line = re.sub(r'CHARACTER SET \w+', '', line)
    line = re.sub(r'COLLATE \w+', '', line)
    # Remove COMMENT '...'
    line = re.sub(r"COMMENT\s+'[^']*'", "", line)
    
    return line

def process_table_block(table_lines, target, current_table):
    # Process column definitions and constraints
    definitions = []
    constraints = []
    indexes = [] # Deferred indexes (Postgres/MSSQL/Oracle)
    primary_key_found = False
    
    # Analyze lines
    for line in table_lines:
        line = line.strip()
        if not line: continue
        
        # Remove trailing comma for processing, will re-add later
        has_comma = line.endswith(',')
        if has_comma:
            content = line[:-1]
        else:
            content = line
            
        # Clean quotes
        # Replace backticks with double quotes for all targets (standard SQL)
        content = content.replace('`', '"')
        
        # Check start
        if content.upper().startswith('PRIMARY KEY'):
            # Standardize PK
            # If SQLite and we already did INTEGER PRIMARY KEY AUTOINCREMENT, skip this?
            if target == 'sqlite' and 'INTEGER PRIMARY KEY AUTOINCREMENT' in ''.join(definitions):
                # We skip separate PK def
                continue
            else:
                definitions.append(content)
                primary_key_found = True
        elif content.upper().startswith('UNIQUE KEY') or content.upper().startswith('UNIQUE INDEX'):
            # Convert to CONSTRAINT UNIQUE
            # MySQL: UNIQUE KEY "name" ("col")
            # Std: CONSTRAINT "name" UNIQUE ("col")
            m = re.match(r'UNIQUE (?:KEY|INDEX)\s+"?(\w+)"?\s+(\(.*\))', content, re.IGNORECASE)
            if m:
                name, cols = m.groups()
                definitions.append(f'CONSTRAINT "{name}" UNIQUE {cols}')
            else:
                definitions.append(content) # Fallback
        elif content.upper().startswith('KEY') or content.upper().startswith('INDEX'):
            # Normal index. Move to deferred.
            # MySQL: KEY "name" ("col")
            # Target: CREATE INDEX "name" ON "table" ("col");
            m = re.match(r'(?:KEY|INDEX)\s+"?(\w+)"?\s+(\(.*\))', content, re.IGNORECASE)
            if m:
                name, cols = m.groups()
                indexes.append(f'CREATE INDEX "{name}" ON "{current_table}" {cols};')
            else:
                # Might be foreign key?
                 definitions.append(content)
        elif content.upper().startswith('CONSTRAINT'):
             # Foreign keys usually
             definitions.append(content)
        else:
             # Column definition
             cleaned = clean_type(content, target)
             definitions.append(cleaned)

    # Reassemble table
    # Join definitions with commas
    body = ',\n  '.join(definitions)
    
    final_sql = []
    # Header
    create_stmt = f'CREATE TABLE IF NOT EXISTS "{current_table}" ('
    if target == 'oracle':
        create_stmt = f'CREATE TABLE "{current_table}" ('
    if target == 'sqlserver':
        # SQL Server doesn't like IF NOT EXISTS in CREATE TABLE definition (Use IF OBJECT_ID.. wrapper generally, but script is simple)
        # We will wrap it in a block? or just ignore error?
        # Better:
        # IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='table' and xtype='U')
        # CREATE TABLE "table" ( ... )
        create_stmt = f'CREATE TABLE "{current_table}" (' 
        # For simplicity in this script we stick to standard SQL or adjust minimal.
        # But we must surround with check if we want idempotency.
        # Let's emit standard CREATE TABLE and let user handle existence checks or wrap:
        final_sql.append(f"IF OBJECT_ID(N'dbo.{current_table}', N'U') IS NULL")
    
    final_sql.append(create_stmt)
    final_sql.append(f"  {body}")
    final_sql.append(");")
    
    # Add indexes
    if indexes:
        final_sql.append("")
        final_sql.extend(indexes)
        
    return '\n'.join(final_sql) + '\n'

def process_inserts(line, target):
    line = line.replace('`', '"')
    line = line.replace("\\'", "''") 
    line = line.replace('\\"', '"')
    return line

def main():
    args = parse_args()
    
    with open(args.input, 'r', encoding='utf-8') as f:
        content = f.read()

    # Pre-processing: MySQL escapes
    content = content.replace("\\'", "''")
    content = content.replace('\\"', '"')

    lines = content.split('\n')
    converted_lines = []
    
    # Headers
    if args.target == 'sqlserver':
        converted_lines.append("SET QUOTED_IDENTIFIER ON;")
    if args.target == 'oracle':
        converted_lines.append("ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';")
        converted_lines.append("ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS';")

    
    table_buffer = []
    in_table = False
    current_table = ""
    
    for line in lines:
        stripped = line.strip()
        if not stripped: continue
        if stripped.startswith('--') or stripped.startswith('/*'): continue
        if 'set @' in stripped.lower(): continue
        
        # Check Table Start
        if 'CREATE TABLE' in line:
            # Extract table name
            m = re.search(r'CREATE TABLE (?:IF NOT EXISTS )?["`]?(\w+)["`]?', line)
            if m:
                current_table = m.group(1)
            in_table = True
            table_buffer = [] # Start buffering (we ignore the content of this first line as we reconstruct it)
            continue
            
        if in_table:
            # Check Table End
            if line.strip().startswith(') ENGINE=') or line.strip() == ');':
                in_table = False
                converted = process_table_block(table_buffer, args.target, current_table)
                converted_lines.append(converted)
                table_buffer = []
            else:
                table_buffer.append(line)
        else:
            # Other lines (Inserts, Drops)
            if 'DROP TABLE' in line:
                m = re.search(r'DROP TABLE (?:IF EXISTS )?["`]?(\w+)["`]?', line)
                tbl = m.group(1) if m else "unknown"
                if args.target == 'sqlserver':
                     converted_lines.append(f"IF OBJECT_ID(N'dbo.{tbl}', N'U') IS NOT NULL DROP TABLE \"{tbl}\";")
                elif args.target == 'oracle':
                     # Oracle DROP lacks IF EXISTS. 
                     converted_lines.append(f"BEGIN EXECUTE IMMEDIATE 'DROP TABLE \"{tbl}\" CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;")
                     converted_lines.append("/")
                elif args.target == 'postgres':
                     converted_lines.append(f'DROP TABLE IF EXISTS "{tbl}" CASCADE;')
                else: 
                     converted_lines.append(process_inserts(line, args.target))
            elif 'INSERT INTO' in line:
                converted_lines.append(process_inserts(line, args.target))
            elif 'CREATE DATABASE' in line:
                if args.target == 'sqlserver':
                    converted_lines.append("IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'capella') BEGIN CREATE DATABASE [capella]; END")
                elif args.target == 'postgres':
                    converted_lines.append("-- " + line + " -- Create DB manually if needed")
                elif args.target == 'oracle':
                    converted_lines.append("-- " + line + " -- Create DB manually")
                else:
                    converted_lines.append(line.replace('`', '"'))
            elif 'USE' in line:
                if args.target == 'oracle':
                    converted_lines.append("-- " + line) # Oracle doesn't USE
                elif args.target == 'postgres':
                    converted_lines.append("-- " + line + " -- Connect to DB manually")
                else:
                    converted_lines.append(line.replace('`', '"'))
            else:
                 # Pass through other lines (like insert values)
                 converted_lines.append(process_inserts(line, args.target))
                 
    output = '\n'.join(converted_lines)
    
    with open(args.output, 'w', encoding='utf-8') as f:
        f.write(output)
    
    print(f"Converted to {args.target}: {args.output}")

if __name__ == "__main__":
    main()
